/**
 * Generic split-tree algebra.
 *
 * Pane renders two layout trees with the same shape and the same drag
 * vocabulary: panel groups inside one Pane (`panelLayout`) and Session tiles
 * across the workspace (`sessionWorkspaceLayout`). The leaf types stay
 * deliberately distinct — a group holds panel ids, a tile holds one Session id
 * — so only the operations that never look inside a leaf live here.
 *
 * Every function is side-effect-free and returns a new tree. Node ids are NEVER
 * regenerated by normalizeTree — React keys depend on their stability.
 *
 * @module layoutTree
 */

export type SplitDirection = 'row' | 'column';

/** The whole contract a leaf owes this module: a discriminant and a stable id. */
export interface LayoutLeaf {
  type: string;
  id: string;
}

/** A branch node: children arranged in a row or column with sash-resizable sizes. */
export interface LayoutSplit<Leaf extends LayoutLeaf> {
  type: 'split';
  id: string;
  direction: SplitDirection;
  children: LayoutTree<Leaf>[];
  sizes: number[];
}

export type LayoutTree<Leaf extends LayoutLeaf> = Leaf | LayoutSplit<Leaf>;

/** A fresh node id. Never regenerated for a surviving node. */
export function newLayoutId(): string {
  return crypto.randomUUID();
}

export function isSplit<Leaf extends LayoutLeaf>(node: LayoutTree<Leaf>): node is LayoutSplit<Leaf> {
  return node.type === 'split';
}

/** Collect every leaf in reading order (depth-first, children left-to-right). */
export function allLeaves<Leaf extends LayoutLeaf>(root: LayoutTree<Leaf>): Leaf[] {
  return isSplit(root) ? root.children.flatMap(child => allLeaves(child)) : [root];
}

/** The first leaf in reading order (leftmost / topmost). */
export function firstLeaf<Leaf extends LayoutLeaf>(root: LayoutTree<Leaf>): Leaf {
  return isSplit(root) ? firstLeaf(root.children[0]) : root;
}

/** Find a leaf by id. */
export function findLeaf<Leaf extends LayoutLeaf>(root: LayoutTree<Leaf>, leafId: string): Leaf | null {
  if (!isSplit(root)) return root.id === leafId ? root : null;
  for (const child of root.children) {
    const found = findLeaf(child, leafId);
    if (found) return found;
  }
  return null;
}

/** Whether a subtree contains a given leaf id. */
export function containsLeaf<Leaf extends LayoutLeaf>(node: LayoutTree<Leaf>, leafId: string): boolean {
  return isSplit(node)
    ? node.children.some(child => containsLeaf(child, leafId))
    : node.id === leafId;
}

/** Rewrite every leaf, leaving the structure alone. */
export function mapLeaves<Leaf extends LayoutLeaf>(
  root: LayoutTree<Leaf>,
  transform: (leaf: Leaf) => Leaf,
): LayoutTree<Leaf> {
  if (!isSplit(root)) return transform(root);
  return { ...root, children: root.children.map(child => mapLeaves(child, transform)) };
}

/**
 * Normalize the tree:
 * - Drop leaves `isEmptyLeaf` reports as empty.
 * - Replace single-child splits with the child.
 * - Merge same-direction nested splits (flatten).
 * - Renormalize sizes to sum 1.
 *
 * Returns null when nothing survives; callers decide what an empty tree means.
 * CRITICAL: preserve every surviving node's id.
 */
export function normalizeTree<Leaf extends LayoutLeaf>(
  root: LayoutTree<Leaf>,
  isEmptyLeaf: (leaf: Leaf) => boolean,
): LayoutTree<Leaf> | null {
  if (!isSplit(root)) return isEmptyLeaf(root) ? null : root;

  // Recurse children first
  let children: LayoutTree<Leaf>[] = [];
  let sizes: number[] = [];
  for (let i = 0; i < root.children.length; i++) {
    const child = normalizeTree(root.children[i], isEmptyLeaf);
    if (!child) continue;
    children.push(child);
    sizes.push(root.sizes[i] ?? 1);
  }

  if (children.length === 0) return null;

  // Single child: unwrap
  if (children.length === 1) return children[0];

  // Flatten same-direction nested splits
  const flatChildren: LayoutTree<Leaf>[] = [];
  const flatSizes: number[] = [];
  const totalSize = sizes.reduce((a, b) => a + b, 0) || 1;
  for (let i = 0; i < children.length; i++) {
    const child = children[i];
    const childProportion = sizes[i] / totalSize;
    if (isSplit(child) && child.direction === root.direction) {
      const childTotal = child.sizes.reduce((a, b) => a + b, 0) || 1;
      for (let j = 0; j < child.children.length; j++) {
        flatChildren.push(child.children[j]);
        flatSizes.push(childProportion * (child.sizes[j] / childTotal));
      }
    } else {
      flatChildren.push(child);
      flatSizes.push(childProportion);
    }
  }

  children = flatChildren;
  sizes = flatSizes;

  // Renormalize sizes to sum 1
  const sizeSum = sizes.reduce((a, b) => a + b, 0) || 1;
  sizes = sizes.map(s => s / sizeSum);

  return { ...root, children, sizes };
}

/** Update the sizes array of one split node, found by id. */
export function updateSplitSizes<Leaf extends LayoutLeaf>(
  root: LayoutTree<Leaf>,
  splitNodeId: string,
  newSizes: number[],
): LayoutTree<Leaf> {
  if (!isSplit(root)) return root;
  if (root.id === splitNodeId) return { ...root, sizes: newSizes };
  return { ...root, children: root.children.map(child => updateSplitSizes(child, splitNodeId, newSizes)) };
}

/**
 * Insert `leaf` next to the leaf `targetLeafId`.
 *
 * N-ary rule: if the parent split already runs in `direction`, insert as a
 * sibling (no nesting). Only wrap in a new split node when the direction
 * differs or the target is the root.
 */
export function insertLeafBeside<Leaf extends LayoutLeaf>(
  root: LayoutTree<Leaf>,
  targetLeafId: string,
  leaf: Leaf,
  direction: SplitDirection,
  after: boolean,
): LayoutTree<Leaf> {
  function insert(node: LayoutTree<Leaf>): LayoutTree<Leaf> {
    if (!isSplit(node)) {
      if (node.id !== targetLeafId) return node;
      // Target is the root or a leaf — wrap it in a new split.
      return {
        type: 'split',
        id: newLayoutId(),
        direction,
        children: after ? [node, leaf] : [leaf, node],
        sizes: [0.5, 0.5],
      };
    }
    const index = node.children.findIndex(child => child.id === targetLeafId);
    if (index !== -1 && node.direction === direction) {
      // Same direction: insert as a sibling in the existing split (n-ary).
      // The new leaf takes half the target's size, then sizes renormalize.
      const children = [...node.children];
      const sizes = [...node.sizes];
      const half = (sizes[index] ?? 1) / 2;
      sizes[index] = half;
      const at = after ? index + 1 : index;
      children.splice(at, 0, leaf);
      sizes.splice(at, 0, half);
      return { ...node, children, sizes };
    }
    return { ...node, children: node.children.map(insert) };
  }

  return insert(root);
}

/** Remove one leaf by id and normalize. Returns null when the tree collapses. */
export function removeLeaf<Leaf extends LayoutLeaf>(
  root: LayoutTree<Leaf>,
  leafId: string,
  isEmptyLeaf: (leaf: Leaf) => boolean,
): LayoutTree<Leaf> | null {
  function prune(node: LayoutTree<Leaf>): LayoutTree<Leaf> | null {
    if (!isSplit(node)) return node.id === leafId ? null : node;
    const children: LayoutTree<Leaf>[] = [];
    const sizes: number[] = [];
    node.children.forEach((child, index) => {
      const kept = prune(child);
      if (!kept) return;
      children.push(kept);
      sizes.push(node.sizes[index] ?? 1);
    });
    if (children.length === 0) return null;
    return { ...node, children, sizes };
  }

  const pruned = prune(root);
  return pruned ? normalizeTree(pruned, isEmptyLeaf) : null;
}

// ---------------------------------------------------------------------------
// Geometry (for directional focus)
// ---------------------------------------------------------------------------

export interface LayoutRect {
  x: number;
  y: number;
  w: number;
  h: number;
}

/** Assign each leaf a rect in unit space [0,1]x[0,1]. */
export function leafRects<Leaf extends LayoutLeaf>(root: LayoutTree<Leaf>): Map<string, LayoutRect> {
  const result = new Map<string, LayoutRect>();

  function walk(node: LayoutTree<Leaf>, x: number, y: number, w: number, h: number) {
    if (!isSplit(node)) {
      result.set(node.id, { x, y, w, h });
      return;
    }
    const totalSize = node.sizes.reduce((a, b) => a + b, 0) || 1;
    let offset = 0;
    for (let i = 0; i < node.children.length; i++) {
      const proportion = (node.sizes[i] ?? 1) / totalSize;
      if (node.direction === 'row') {
        walk(node.children[i], x + offset * w, y, proportion * w, h);
      } else {
        walk(node.children[i], x, y + offset * h, w, proportion * h);
      }
      offset += proportion;
    }
  }

  walk(root, 0, 0, 1, 1);
  return result;
}

export type LayoutDirection = 'left' | 'right' | 'up' | 'down';

/**
 * Find the nearest leaf in a direction from `fromLeafId`.
 * Uses geometric overlap: the leaf across that edge with the most perpendicular
 * overlap wins, nearest first on a tie.
 */
export function findLeafInDirection<Leaf extends LayoutLeaf>(
  root: LayoutTree<Leaf>,
  fromLeafId: string,
  dir: LayoutDirection,
): string | null {
  const rects = leafRects(root);
  const from = rects.get(fromLeafId);
  if (!from) return null;

  const eps = 0.001;
  let best: string | null = null;
  let bestOverlap = -1;
  let bestDist = Infinity;

  for (const [leafId, rect] of rects) {
    if (leafId === fromLeafId) continue;

    let isCandidate = false;
    let overlap = 0;
    let dist = 0;

    switch (dir) {
      case 'right':
        isCandidate = rect.x >= from.x + from.w - eps;
        overlap = Math.max(0, Math.min(from.y + from.h, rect.y + rect.h) - Math.max(from.y, rect.y));
        dist = rect.x - (from.x + from.w);
        break;
      case 'left':
        isCandidate = rect.x + rect.w <= from.x + eps;
        overlap = Math.max(0, Math.min(from.y + from.h, rect.y + rect.h) - Math.max(from.y, rect.y));
        dist = from.x - (rect.x + rect.w);
        break;
      case 'down':
        isCandidate = rect.y >= from.y + from.h - eps;
        overlap = Math.max(0, Math.min(from.x + from.w, rect.x + rect.w) - Math.max(from.x, rect.x));
        dist = rect.y - (from.y + from.h);
        break;
      case 'up':
        isCandidate = rect.y + rect.h <= from.y + eps;
        overlap = Math.max(0, Math.min(from.x + from.w, rect.x + rect.w) - Math.max(from.x, rect.x));
        dist = from.y - (rect.y + rect.h);
        break;
    }

    if (isCandidate && overlap > 0) {
      if (overlap > bestOverlap || (overlap === bestOverlap && dist < bestDist)) {
        best = leafId;
        bestOverlap = overlap;
        bestDist = dist;
      }
    }
  }

  return best;
}

// ---------------------------------------------------------------------------
// Drop zones
// ---------------------------------------------------------------------------

export type DropZone = 'left' | 'right' | 'top' | 'bottom' | 'center';
export type DropEdge = Exclude<DropZone, 'center'>;

/**
 * Determine which drop zone the cursor is in within a rect.
 * 25% edge bands; center otherwise.
 */
export function dropZoneFor(clientX: number, clientY: number, rect: DOMRect): DropZone {
  const rx = (clientX - rect.left) / rect.width;
  const ry = (clientY - rect.top) / rect.height;
  const d = Math.min(rx, 1 - rx, ry, 1 - ry);
  if (d > 0.25) return 'center';
  // Nearest edge wins
  const edges: [DropZone, number][] = [
    ['left', rx],
    ['right', 1 - rx],
    ['top', ry],
    ['bottom', 1 - ry],
  ];
  edges.sort((a, b) => a[1] - b[1]);
  return edges[0][0];
}

/** Which axis an edge drop splits on, and which side of the target it lands. */
export interface EdgeSplit {
  direction: SplitDirection;
  after: boolean;
}

/** How an edge drop splits against its target. */
export function splitForEdge(edge: DropEdge): EdgeSplit {
  return {
    direction: edge === 'left' || edge === 'right' ? 'row' : 'column',
    after: edge === 'right' || edge === 'bottom',
  };
}
