/**
 * Pure layout tree operations for split tab groups.
 *
 * Every function here is side-effect-free and returns a new tree.
 * Node ids are NEVER regenerated by normalize — React keys depend on stability.
 *
 * The tree algebra that never looks inside a group — normalize, sizes, geometry,
 * sibling insertion, drop zones — lives in `layoutTree` and is shared with the
 * Session tile tree. Only panel-aware operations are implemented here.
 *
 * @module panelLayout
 */

import type {
  PanelGroupNode,
  PanelLayoutNode,
  SessionPanelLayout,
} from '../../../shared/types/panels';
import {
  allLeaves,
  containsLeaf,
  findLeaf,
  findLeafInDirection,
  firstLeaf,
  insertLeafBeside,
  leafRects,
  newLayoutId,
  normalizeTree,
  splitForEdge,
  updateSplitSizes,
} from './layoutTree';
import type { LayoutRect } from './layoutTree';

export { dropZoneFor } from './layoutTree';
export type { DropZone } from './layoutTree';

interface ReconciledPanelLayout {
  layout: SessionPanelLayout;
  changed: boolean;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function newId(): string {
  return newLayoutId();
}

/** A group with no tabs left; normalize drops these. */
function isEmptyGroup(group: PanelGroupNode): boolean {
  return group.panelIds.length === 0;
}

/** Find the first group in reading order (leftmost / topmost leaf). */
export function primaryGroup(root: PanelLayoutNode): PanelGroupNode {
  return firstLeaf<PanelGroupNode>(root);
}

/** Collect all group nodes in reading order (depth-first, children left-to-right). */
export function allGroups(root: PanelLayoutNode): PanelGroupNode[] {
  return allLeaves<PanelGroupNode>(root);
}

/** Collect all panel ids referenced by the layout tree. */
export function allPanelIds(root: PanelLayoutNode): string[] {
  if (root.type === 'group') return [...root.panelIds];
  return root.children.flatMap(allPanelIds);
}

/** Find a group node by id. */
export function findGroup(root: PanelLayoutNode, groupId: string): PanelGroupNode | null {
  return findLeaf<PanelGroupNode>(root, groupId);
}

/** Check whether a subtree contains a given group id. */
export function containsGroup(node: PanelLayoutNode, groupId: string): boolean {
  return containsLeaf<PanelGroupNode>(node, groupId);
}

/** Find which group contains a given panelId. */
export function findGroupContainingPanel(root: PanelLayoutNode, panelId: string): PanelGroupNode | null {
  if (root.type === 'group') return root.panelIds.includes(panelId) ? root : null;
  for (const child of root.children) {
    const found = findGroupContainingPanel(child, panelId);
    if (found) return found;
  }
  return null;
}

/** Activate a panel and focus its containing group without changing the tree structure. */
export function activatePanelInLayout(
  layout: SessionPanelLayout,
  panelId: string,
): SessionPanelLayout {
  const group = findGroupContainingPanel(layout.root, panelId);
  if (!group) return layout;
  const groupId = group.id;

  function activate(node: PanelLayoutNode): PanelLayoutNode {
    if (node.type === 'group') {
      return node.id === groupId ? { ...node, activePanelId: panelId } : node;
    }
    return { ...node, children: node.children.map(activate) };
  }

  return {
    ...layout,
    root: activate(layout.root),
    focusedGroupId: groupId,
    zoomedGroupId: layout.zoomedGroupId && layout.zoomedGroupId !== groupId
      ? null
      : layout.zoomedGroupId,
  };
}

// ---------------------------------------------------------------------------
// Create
// ---------------------------------------------------------------------------

/** Create a single-group layout from an ordered list of panel ids. */
export function createSingleGroupLayout(
  panelIds: string[],
  activePanelId: string | null,
): SessionPanelLayout {
  const groupId = newId();
  return {
    version: 1,
    root: {
      type: 'group',
      id: groupId,
      panelIds,
      activePanelId: activePanelId && panelIds.includes(activePanelId) ? activePanelId : panelIds[0] ?? null,
    },
    focusedGroupId: groupId,
  };
}

/**
 * Add a panel to a group. Idempotent: if the panel id already exists anywhere
 * in the tree, the tree is returned unchanged. This guards against the
 * create-path double-append (handlePanelCreate and the panel:created event
 * both try to insert the same panel).
 */
export function addPanelToGroup(
  root: PanelLayoutNode,
  groupId: string,
  panelId: string,
  options: { activate?: boolean } = {},
): PanelLayoutNode {
  if (allPanelIds(root).includes(panelId)) return root;
  const activate = options.activate !== false;

  function insert(node: PanelLayoutNode): PanelLayoutNode {
    if (node.type === 'group') {
      if (node.id !== groupId) return node;
      const activePanelId = activate || !node.activePanelId
        ? panelId
        : node.activePanelId;
      return {
        ...node,
        panelIds: [...node.panelIds, panelId],
        activePanelId,
      };
    }
    return { ...node, children: node.children.map(insert) };
  }

  return insert(root);
}

/**
 * Open a panel beside the primary group: as a tab in the last other group, or
 * in a new right-hand group when the layout has only one. Idempotent like
 * addPanelToGroup.
 */
export function placePanelInSplit(root: PanelLayoutNode, panelId: string, activate = true): PanelLayoutNode {
  if (allPanelIds(root).includes(panelId)) return root;
  const primary = primaryGroup(root);
  const side = allGroups(root).filter(group => group.id !== primary.id).pop();
  return side
    ? addPanelToGroup(root, side.id, panelId, { activate })
    : splitGroup(root, primary.id, panelId, 'row', true);
}

// ---------------------------------------------------------------------------
// Normalize
// ---------------------------------------------------------------------------

/**
 * Normalize the tree:
 * - Drop empty groups.
 * - Replace single-child splits with the child.
 * - Merge same-direction nested splits (flatten).
 * - Renormalize sizes to sum 1.
 * CRITICAL: preserve every surviving node's id.
 */
export function normalize(root: PanelLayoutNode): PanelLayoutNode {
  const normalized = normalizeTree<PanelGroupNode>(root, isEmptyGroup);
  if (normalized) return normalized;
  // Nothing survived. Keep one empty group so the caller still has a tree to
  // land new panels in (reconcile and the close paths handle the empty case).
  return root.type === 'group' ? root : { type: 'group', id: root.id, panelIds: [], activePanelId: null };
}

// ---------------------------------------------------------------------------
// Split
// ---------------------------------------------------------------------------

/**
 * Split a group: move `panelId` out of `sourceGroupId` into a new sibling group.
 *
 * N-ary rule: if the parent split already runs in `direction`, insert as a sibling
 * (no nesting). Only wrap in a new split node when the direction differs or
 * the group is the root.
 */
export function splitGroup(
  root: PanelLayoutNode,
  sourceGroupId: string,
  panelId: string,
  direction: 'row' | 'column',
  after = true,
): PanelLayoutNode {
  const newGroupId = newId();
  const newGroup: PanelGroupNode = {
    type: 'group',
    id: newGroupId,
    panelIds: [panelId],
    activePanelId: panelId,
  };

  function removePanel(node: PanelLayoutNode): PanelLayoutNode {
    if (node.type === 'group') {
      if (node.id !== sourceGroupId) return node;
      const filtered = node.panelIds.filter(id => id !== panelId);
      return {
        ...node,
        panelIds: filtered,
        activePanelId: node.activePanelId === panelId
          ? (filtered[0] ?? null)
          : node.activePanelId,
      };
    }
    return {
      ...node,
      children: node.children.map(removePanel),
    };
  }

  // 1. Remove panelId from source group
  const afterRemove = removePanel(root);
  // 2. Insert the new group next to the source
  const afterInsert = insertLeafBeside<PanelGroupNode>(afterRemove, sourceGroupId, newGroup, direction, after);
  // 3. Normalize
  return normalize(afterInsert);
}

// ---------------------------------------------------------------------------
// Move panel
// ---------------------------------------------------------------------------


interface MoveTargetCenter {
  groupId: string;
  index: number;
}

interface MoveTargetEdge {
  groupId: string;
  edge: 'left' | 'right' | 'top' | 'bottom';
}

export type MoveTarget = MoveTargetCenter | MoveTargetEdge;

function isCenterTarget(t: MoveTarget): t is MoveTargetCenter {
  return 'index' in t;
}

/**
 * Move a panel: center drop inserts into target group at index;
 * edge drop splits against the target.
 */
export function movePanel(
  root: PanelLayoutNode,
  panelId: string,
  target: MoveTarget,
): PanelLayoutNode {
  // Remove from source
  function removePanelFromTree(node: PanelLayoutNode): PanelLayoutNode {
    if (node.type === 'group') {
      if (!node.panelIds.includes(panelId)) return node;
      const filtered = node.panelIds.filter(id => id !== panelId);
      return {
        ...node,
        panelIds: filtered,
        activePanelId: node.activePanelId === panelId
          ? (filtered[0] ?? null)
          : node.activePanelId,
      };
    }
    return { ...node, children: node.children.map(removePanelFromTree) };
  }

  if (isCenterTarget(target)) {
    // Center: insert into the target group at index. target.index is based on
    // the pre-removal tab order, so a same-group move to a later position must
    // shift left by one or it lands one slot past the drop indicator.
    const centerTarget = target;
    let insertIndex = centerTarget.index;
    const targetGroup = findGroup(root, centerTarget.groupId);
    if (targetGroup) {
      const sourceIdx = targetGroup.panelIds.indexOf(panelId);
      if (sourceIdx !== -1 && sourceIdx < insertIndex) insertIndex -= 1;
    }
    const removed = removePanelFromTree(root);
    function insertIntoGroup(node: PanelLayoutNode): PanelLayoutNode {
      if (node.type === 'group' && node.id === centerTarget.groupId) {
        const newPanelIds = [...node.panelIds];
        const insertIdx = Math.min(insertIndex, newPanelIds.length);
        newPanelIds.splice(insertIdx, 0, panelId);
        return { ...node, panelIds: newPanelIds, activePanelId: panelId };
      }
      if (node.type === 'split') {
        return { ...node, children: node.children.map(insertIntoGroup) };
      }
      return node;
    }
    return normalize(insertIntoGroup(removed));
  }

  // Edge: this is a split. Remove the panel, then split against the target group.
  const removed = removePanelFromTree(root);
  const normalized = normalize(removed);

  // SAFETY: The surrounding typed producer establishes the narrower value shape consumed here.
  const edgeTarget = target as MoveTargetEdge;
  const { direction, after } = splitForEdge(edgeTarget.edge);

  // We need to create a new group beside the target group
  const newGroup: PanelGroupNode = {
    type: 'group',
    id: newId(),
    panelIds: [panelId],
    activePanelId: panelId,
  };

  return normalize(insertLeafBeside<PanelGroupNode>(normalized, edgeTarget.groupId, newGroup, direction, after));
}

// ---------------------------------------------------------------------------
// Remove panel from layout (for close)
// ---------------------------------------------------------------------------

/**
 * Remove a panel id from the layout. Returns null if the tree collapses entirely.
 */
export function removePanelFromLayout(
  root: PanelLayoutNode,
  panelId: string,
): PanelLayoutNode | null {
  function remove(node: PanelLayoutNode): PanelLayoutNode {
    if (node.type === 'group') {
      if (!node.panelIds.includes(panelId)) return node;
      const filtered = node.panelIds.filter(id => id !== panelId);
      return {
        ...node,
        panelIds: filtered,
        activePanelId: node.activePanelId === panelId
          ? (filtered[0] ?? null)
          : node.activePanelId,
      };
    }
    return { ...node, children: node.children.map(remove) };
  }

  const result = normalize(remove(root));
  // If the entire tree collapsed to an empty group, return null
  if (result.type === 'group' && result.panelIds.length === 0) return null;
  return result;
}

// ---------------------------------------------------------------------------
// Reconcile
// ---------------------------------------------------------------------------

/**
 * Reconcile a stored layout against the current live panel ids.
 * - Prune panel ids not in livePanelIds.
 * - Append unassigned live panels to the primary group.
 * - Fix activePanelId per group.
 * - Guarantee at least one group.
 */
export function reconcile(
  layout: SessionPanelLayout,
  livePanelIds: string[],
  splitPanelIds: ReadonlySet<string> = new Set(),
): ReconciledPanelLayout {
  const liveSet = new Set(livePanelIds);
  let changed = false;
  // A panel id may only appear once across the whole tree; keep the first
  // occurrence in reading order and drop duplicates.
  const seen = new Set<string>();

  function cleanNode(node: PanelLayoutNode): PanelLayoutNode {
    if (node.type === 'group') {
      const filtered = node.panelIds.filter(id => {
        if (!liveSet.has(id) || seen.has(id)) { changed = true; return false; }
        seen.add(id);
        return true;
      });
      const active = filtered.includes(node.activePanelId ?? '') ? node.activePanelId : (filtered[0] ?? null);
      if (active !== node.activePanelId) changed = true;
      return { ...node, panelIds: filtered, activePanelId: active };
    }
    return { ...node, children: node.children.map(cleanNode) };
  }

  let root = normalize(cleanNode(layout.root));

  // If the tree collapsed, recreate with a single group
  if (root.type === 'group' && root.panelIds.length === 0 && livePanelIds.length > 0) {
    changed = true;
    // Keep agent-opened splits unassigned so the placement pass can put them
    // beside the conversation. With only split panels, one anchors the layout.
    const primaryIds = livePanelIds.filter(id => !splitPanelIds.has(id));
    const initialIds = primaryIds.length > 0 ? primaryIds : livePanelIds.slice(0, 1);
    root = {
      type: 'group',
      id: root.id,
      panelIds: initialIds,
      activePanelId: initialIds[0],
    };
  }

  // Find orphans (live panels not in the tree)
  const assigned = new Set(allPanelIds(root));
  const unassigned = livePanelIds.filter(id => !assigned.has(id));
  const orphans = unassigned.filter(id => !splitPanelIds.has(id));
  for (const id of unassigned) {
    if (!splitPanelIds.has(id)) continue;
    changed = true;
    root = placePanelInSplit(root, id);
  }
  if (orphans.length > 0) {
    changed = true;
    const primary = primaryGroup(root);
    // We need to mutate the tree to add orphans to the primary group
    function addOrphansToPrimary(node: PanelLayoutNode): PanelLayoutNode {
      if (node.type === 'group' && node.id === primary.id) {
        return {
          ...node,
          panelIds: [...node.panelIds, ...orphans],
          activePanelId: node.activePanelId ?? orphans[0],
        };
      }
      if (node.type === 'split') {
        return { ...node, children: node.children.map(addOrphansToPrimary) };
      }
      return node;
    }
    root = addOrphansToPrimary(root);
  }

  // Validate focusedGroupId
  let focusedGroupId = layout.focusedGroupId;
  if (!focusedGroupId || !findGroup(root, focusedGroupId)) {
    focusedGroupId = primaryGroup(root).id;
    changed = true;
  }

  // Validate zoomedGroupId
  let zoomedGroupId = layout.zoomedGroupId;
  if (zoomedGroupId && !findGroup(root, zoomedGroupId)) {
    zoomedGroupId = null;
    changed = true;
  }

  return {
    layout: { ...layout, root, focusedGroupId, zoomedGroupId },
    changed,
  };
}

// ---------------------------------------------------------------------------
// Merge all groups (the un-split gesture)
// ---------------------------------------------------------------------------

/**
 * Collapse the entire tree into the primary group. Panel order: the primary
 * group's panels first, then the remaining groups' panels in reading order.
 * The primary group's id and active tab survive.
 */
export function mergeAllGroups(root: PanelLayoutNode): PanelGroupNode {
  if (root.type === 'group') return root;
  const primary = primaryGroup(root);
  const seen = new Set<string>();
  const ids: string[] = [];
  for (const id of allPanelIds(root)) {
    if (!seen.has(id)) {
      seen.add(id);
      ids.push(id);
    }
  }
  return {
    type: 'group',
    id: primary.id,
    panelIds: ids,
    activePanelId: primary.activePanelId ?? ids[0] ?? null,
  };
}

// ---------------------------------------------------------------------------
// Subset index translation
// ---------------------------------------------------------------------------

/**
 * Translate an insertion index within a displayed subset of a group's tabs
 * (e.g. a strip showing only non-permanent tabs while the permanent ones stay
 * in the top bar) into an insertion index in the group's full panel order.
 * The subset must preserve the full order's relative ordering.
 */
export function subsetInsertIndex(
  fullIds: string[],
  subsetIds: string[],
  subsetIndex: number,
): number {
  if (subsetIndex >= subsetIds.length) {
    const last = subsetIds[subsetIds.length - 1];
    if (last === undefined) return fullIds.length;
    const i = fullIds.indexOf(last);
    return i === -1 ? fullIds.length : i + 1;
  }
  const i = fullIds.indexOf(subsetIds[subsetIndex]);
  return i === -1 ? fullIds.length : i;
}

// ---------------------------------------------------------------------------
// Update sizes
// ---------------------------------------------------------------------------

/**
 * Update the sizes array for a specific split node by id.
 */
export function updateSizes(
  root: PanelLayoutNode,
  splitNodeId: string,
  newSizes: number[],
): PanelLayoutNode {
  return updateSplitSizes<PanelGroupNode>(root, splitNodeId, newSizes);
}

// ---------------------------------------------------------------------------
// Geometry (for directional focus)
// ---------------------------------------------------------------------------

export type GroupRect = LayoutRect;

/** Assign each group a rect in unit space [0,1]x[0,1]. */
export function groupRects(root: PanelLayoutNode): Map<string, GroupRect> {
  return leafRects<PanelGroupNode>(root);
}

/**
 * Find the nearest group in a direction from the focused group.
 * Uses geometric overlap: pick the group across the focused edge with max perpendicular overlap.
 */
export function findGroupInDirection(
  root: PanelLayoutNode,
  fromGroupId: string,
  dir: 'left' | 'right' | 'up' | 'down',
): string | null {
  return findLeafInDirection<PanelGroupNode>(root, fromGroupId, dir);
}
